### ISSUE TITLE
No-latin chaaracters are not encoded correctly in the results

### ISSUE THREAD

**Issue by phtrceh** [NERC-EDS/citationNotebook#1]
e.g. "PubCitationStr": "Казун, А. (2021). Профессиональные табу в деятельности политических консультантов. In Полис. Политические исследования (Issue 1, pp. 157–168). Non Profit Partnership Polis (Political Studies). https://doi.org/10.17976/jpps/2021.01.11"

is returned as 

     "PubCitationStr": "\u00d0\u009a\u00d0\u00b0\u00d0\u00b7\u00d1\u0083\u00d0\u00bd, \u00d0\u0090. (2021). \u00d0\u009f\u00d1\u0080\u00d0\u00be\u00d1\u0084\u00d0\u00b5\u00d1\u0081\u00d1\u0081\u00d0\u00b8\u00d0\u00be\u00d0\u00bd\u00d0\u00b0\u00d0\u00bb\u00d1\u008c\u00d0\u00bd\u00d1\u008b\u00d0\u00b5 \u00d1\u0082\u00d0\u00b0\u00d0\u00b1\u00d1\u0083 \u00d0\u00b2 \u00d0\u00b4\u00d0\u00b5\u00d1\u008f\u00d1\u0082\u00d0\u00b5\u00d0\u00bb\u00d1\u008c\u00d0\u00bd\u00d0\u00be\u00d1\u0081\u00d1\u0082\u00d0\u00b8 \u00d0\u00bf\u00d0\u00be\u00d0\u00bb\u00d0\u00b8\u00d1\u0082\u00d0\u00b8\u00d1\u0087\u00d0\u00b5\u00d1\u0081\u00d0\u00ba\u00d0\u00b8\u00d1\u0085 \u00d0\u00ba\u00d0\u00be\u00d0\u00bd\u00d1\u0081\u00d1\u0083\u00d0\u00bb\u00d1\u008c\u00d1\u0082\u00d0\u00b0\u00d0\u00bd\u00d1\u0082\u00d0\u00be\u00d0\u00b2. \u00d0\u009f\u00d0\u00be\u00d0\u00bb\u00d0\u00b8\u00d1\u0081. \u00d0\u009f\u00d0\u00be\u00d0\u00bb\u00d0\u00b8\u00d1\u0082\u00d0\u00b8\u00d1\u0087\u00d0\u00b5\u00d1\u0081\u00d0\u00ba\u00d0\u00b8\u00d0\u00b5 \u00d0\u0098\u00d1\u0081\u00d1\u0081\u00d0\u00bb\u00d0\u00b5\u00d0\u00b4\u00d0\u00be\u00d0\u00b2\u00d0\u00b0\u00d0\u00bd\u00d0\u00b8\u00d1\u008f, 1, 157\u00e2\u0080\u0093168. https://doi.org/10.17976/jpps/2021.01.11\n"

**Comment by phtrceh** [comment]
Actually - it's not only non-latin characters it may be any non utf-8 character

**Comment by PalaeoMatNic** [comment]
Previously I was created the json from the csv file which may have caused the encoding issues. Now creating the json directly from the dataframe within Python, seems to have fixed the encoding issue. Leaving issue open in case more problems are found.

**Comment by MattHopsonNOC** [comment]
Adding the header "Accept-Charset": "utf-8" to the API call where PubCitationStr is create (cell 32) should resolve this issue.

I created a test script to see:

```
import requests

r = requests.get("https://doi.org/10.21733/ibad.789662", headers={"Accept": "text/x-bibliography", "style": "apa", "Accept-Charset": "utf-8"})

with open("out.txt", "w", encoding="utf-8") as outfile:
    outfile.write(r.text)
```

Using the snippet, the output is:

```
ÇETİN AYDIN, G., AYTAÇ, S., & ŞANLI, Y. (2020). The Effects of Perceived Stress and Stress Symptoms on Nurses’ Tendency to Quit Work. IBAD Sosyal Bilimler Dergisi, 526–538. https://doi.org/10.21733/ibad.789662
```

The same snippet with out the `"Accept-Charset": "utf-8"` header outputs the following:

```
ÃETÄ°N AYDIN, G., AYTAÃ, S., & ÅANLI, Y. (2020). The Effects of Perceived Stress and Stress Symptoms on Nursesâ Tendency to Quit Work. IBAD Sosyal Bilimler Dergisi, 526â538. https://doi.org/10.21733/ibad.789662
```

**Comment by PalaeoMatNic** [comment]
Implemented this in results/v2/latest_results.json 
Let me know if the issue remains!

**Comment by MattHopsonNOC** [comment]
That's perfect looks like it has worked, thanks. 😃
