### ISSUE TITLE
Error in latest output

### ISSUE THREAD

**Issue by phtrceh** [NERC-EDS/citationNotebook#13]
In the latest output the publication_type is wrong quite a lot of the time.  

eg. for 10.5194/hess-24-4853-2020 the publication_type is "Copernicus GmbH".  

I have checked the source data and it is correct so there is a problem with the code that is somehow adding the publisher instead of the publication_type

**Comment by PalaeoMatNic** [comment]
When collecting info on citations from Datacite code (dataCite_fun/getPublicationInfo_timeCopy.py) was collecting 'publisher' rather than 'type'. Changed this and testing now

**Comment by PalaeoMatNic** [comment]
This is now fixed in Results/v2/latest_results.json in misc_updates_spring24 branch, could you check its as expected?

**Comment by phtrceh** [comment]
The output looks good now, thanks
