### ISSUE TITLE
consistent end-point required for result harvesting

### ISSUE THREAD

**Issue by gap736uk** [NERC-EDS/citationNotebook#2]
To allow catalogues to automatically update their external citation listings there needs to be a reliable end-point which can be harvested from regardless of changes made or when fresh harvesting runs are enacted.

Simple quick win is to also have a 'latest_results' JSON and csv file available which is a copy of the latest harvesting run, whether or not a copy of previous harvesting runs needs to be kept as well.

Ideally, though, an API end-point would be available... but that will take more time to work up.

**Comment by PalaeoMatNic** [comment]
Added some code to write the results to 'latest_results.csv' and  'latest_results.json'. Kept the lines that write the data to dataCitations_allSourcesMerged_retrieved_05052023.csv, for example, so we have a record of results.

**Comment by gap736uk** [comment]
Suggestion from meeting on 24th Jul was :

Result/v1/<latest files>

Then if there are alterations to the output structure then new version dirs can be added in to allow a consistent end point to avoid break in service for others.

**Comment by PalaeoMatNic** [comment]
Results are now found at Result/v1/latest_results.json
