### ISSUE TITLE
Add data doi url  and publication url to the json

### ISSUE THREAD

**Issue by JamesAyliffe** [NERC-EDS/citationNotebook#9]
This would allow users to access the urls for relevant DOIs from a given API call

**Comment by PalaeoMatNic** [comment]
Added new keys 'publication_doi_url' and 'data_doi_url' which is, for example, 'doi.org/' +  'data_doi' i.e. ‘doi.org/10.5285/a29c5465-b138-234d-e053-6c86abc040b9’
This version of  latest_results.json will need to go in a new folder 'results/v2'
Will need to commit new latest_results.json file so won't appear immediately
